COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= oor_read_sensor_data_normal_mode.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bmp5.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk